ZIMBRA-95: Related Contacts
Zimbra/zm-solr pull request #3
Opened 2017-11-22 20:58 UTC by ilyusha

"events" configset schema updates for related contacts functionality
 - point numeric fields are incompatible with streaming queries, so changed `ev_timestamp` and `msg_id` to types  "date" and "int".
 - added `zmaddress` field type that uses `ZimbraAddressTokenizerFactory` for tokenizing input
 - dynamic field definition `*_zaddr` uses `zmaddress` field type. This allows for searching for addresses in denormalized sender and recipient event fields.
 - `*zaddr` fields are copied to stored `*_s` dynamic field for retrieval

2017-11-23 10:51 UTC, fatkudu requested changes
You tend to put really great comments in the pull request details.  In this case, the commit comment is a lot less informative.  From a historical point of view, I think commit comments are extremely useful for determining why changes were made and are significantly easier (I think??)  to find than assoicated pull requests.  Could the commit comment be updated to be similar to the pull request comment please?
Other than that, all seems to make sense.

2017-11-24 20:06 UTC, ilyusha commented
@fatkudu Sure thing, I'll elaborate on the reasons for these changes.

2017-11-27 15:00 UTC, tmclane approved these changes
Definitely agree with Gren regarding the comment quality!  You lead a good example for sure!

2017-11-28 16:23 UTC, gordyt approved these changes

2017-11-29 17:03 UTC, merged